#!/usr/bin/env bash
# Rebuilds the two generated files the workshop's shared editing needs, from a PuzzleScript-labs
# checkout and npm:
#
#   activity/workshop/codemirror6-runtime.js
#     The labs editor's CodeMirror 6 runtime (its own source file, at the package versions labs
#     pins) with @codemirror/collab bundled in beside it. Collaboration has to share one copy of
#     @codemirror/state with the editor, so it cannot be a separate file; and building it here
#     leaves labs' own curated bundle exactly as it is. The workshop page loads this file where
#     the labs page loads its own runtime.
#
#   vendor/codemirror-state.cjs
#     The same @codemirror/state for node, with which the bot applies each change to its copy of
#     the document.
#
# Both are committed. Run this when labs changes its runtime source or its CodeMirror versions;
# deploy.sh refuses to deploy a runtime built from a different labs source.
set -euo pipefail
COLLAB_VERSION="6.1.1"
ESBUILD_VERSION="0.28.2"
HERE="$(cd "$(dirname "$0")/.." && pwd)"
ROOT="$(cd "$HERE/.." && pwd)"
LABS="${PUZZLESCRIPT_LABS_DIR:-$ROOT/../PuzzleScript-labs/.claude/worktrees/discord-workshop}"
SOURCE="$LABS/src/js/codemirror6/runtime/source/index.js"
[ -f "$SOURCE" ] || { echo "no labs runtime source at $SOURCE" >&2; exit 1; }
SOURCE_HASH="$(shasum -a 256 "$SOURCE" | cut -d' ' -f1)"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

# A package.json holding labs' CodeMirror packages at labs' versions, plus collab and the bundler.
LABS="$LABS" COLLAB_VERSION="$COLLAB_VERSION" ESBUILD_VERSION="$ESBUILD_VERSION" node -e '
const labs = require(process.env.LABS + "/package.json").dependencies;
const deps = {};
for (const [name, version] of Object.entries(labs)) if (/^@(codemirror|lezer)\//.test(name)) deps[name] = version;
const versions = JSON.stringify(deps);
deps["@codemirror/collab"] = process.env.COLLAB_VERSION;
deps.esbuild = process.env.ESBUILD_VERSION;
require("fs").writeFileSync("'"$TMP"'/package.json", JSON.stringify({ private: true, dependencies: deps }));
require("fs").writeFileSync("'"$TMP"'/versions.json", versions);
'
cp "$SOURCE" "$TMP/labs-runtime.js"
cat > "$TMP/entry.mjs" <<'JS'
import "./labs-runtime.js"
import {collab, getClientID, getSyncedVersion, receiveUpdates, sendableUpdates} from "@codemirror/collab"
import {ChangeSet, Compartment} from "@codemirror/state"

// What the workshop needs beyond the names the editor's own runtime gives out.
globalThis.PuzzleScriptWorkshopCollab = Object.freeze({
  collab, getClientID, getSyncedVersion, receiveUpdates, sendableUpdates, ChangeSet, Compartment
})
JS
printf 'module.exports = require("@codemirror/state")\n' > "$TMP/state.cjs"
cd "$TMP"
npm install --no-audit --no-fund >/dev/null
STATE_VERSION="$(node -p 'JSON.parse(require("fs").readFileSync("node_modules/@codemirror/state/package.json", "utf8")).version')"
mkdir -p "$HERE/activity/workshop" "$HERE/vendor"
npx esbuild entry.mjs --bundle --format=iife --minify --target=chrome110,firefox110,safari16,edge110 \
  --define:__PUZZLESCRIPT_CM6_VERSIONS__="$(cat versions.json)" \
  --banner:js="/* GENERATED by scripts/build-workshop-runtime.sh — do not edit. labs runtime source sha256:$SOURCE_HASH, @codemirror/collab $COLLAB_VERSION */" \
  --outfile="$HERE/activity/workshop/codemirror6-runtime.js"
npx esbuild state.cjs --bundle --platform=node --format=cjs --minify \
  --banner:js="/* GENERATED by scripts/build-workshop-runtime.sh — do not edit. @codemirror/state $STATE_VERSION */" \
  --outfile="$HERE/vendor/codemirror-state.cjs"
